version: '3.7'
services:
  php:
    container_name: php
    build:
      context: ./docker/php
    depends_on:
      - mysql
    ports:
      - '9000:9000'
    volumes:
      - ./laravel:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/exc/php-fom.d/www.conf
    working_dir: /var/www/html/

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    depends_on:
      - php
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'

  mysql:
    container_name: mysql
    image: mysql:5.7.26
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: password

